### ISSUE TITLE
nontification bar does not disappear when play games while on messenger call.

### ISSUE THREAD

**Issue by mnkh4ntt** [NRanjan-17/Pixel-Experience-Releases#1]
I am not a coding guy so don't know what to put here ;_; ask me if you need anything!

**Comment by NRanjan-17** [comment]
send ss but hide call info

**Comment by mnkh4ntt** [comment]
> send ss but hide call info

Noti bar won't go away neither by itself nor manually.
![Screenshot_20220613-233600_Mobile Legends_ Bang Bang](https://user-images.githubusercontent.com/101708856/173407674-5c2b2848-b3a4-439d-91e5-f843ca6984c3.png)
![Screenshot_20220613-233648_Mobile Legends_ Bang Bang](https://user-images.githubusercontent.com/101708856/173407691-ccc290a9-42d8-4855-b38e-b65c07bb8702.png)
![Screenshot_20220613-233557_Mobile Legends_ Bang Bang](https://user-images.githubusercontent.com/101708856/173407696-79264ea0-f55b-4dd3-976c-8f34e78f5d2c.png)

**Comment by NRanjan-17** [comment]
Had you checked in other games??

**Comment by NRanjan-17** [comment]
Its working fine for me in games while calls 
But you check in other games and tell use latest build

**Comment by mnkh4ntt** [comment]
I think the problem is with the Fullscreen mode. I found that it wouldn't go away whenever I'm using Fullscreen.For example watching YouTube. Yes I'm using the latest version just updated few days ago. 
Dunno maybe it's specific just for my device even tho I doubt the possibility :)

**Comment by NRanjan-17** [comment]
> I think the problem is with the Fullscreen mode. I found that it wouldn't go away whenever I'm using Fullscreen.For example watching YouTube. Yes I'm using the latest version just updated few days ago. Dunno maybe it's specific just for my device even tho I doubt the possibility :)

Using nav gestures
